replicaCount: 3
image:
  repository: jose-armesto/pong
  tag: latest
service:
  externalPort: 8080
  internalPort: 8080
ingress:
  hosts:
    - pong
  annotations: {}
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
