spring:
  application:
    name: pong
  main:
    banner-mode: "off"

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
      serviceUrl:
        defaultZone: ${EUREKA}
