spring:
  application:
    name: ping
  main:
    banner-mode: "off"
  metrics:
    web:
      server:
        record-request-percentiles: true

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
      serviceUrl:
        defaultZone: ${EUREKA}
